disco:	
	# Compilando a implementacao da fila
	gcc -c implementacao_disco.c -o disco.o
	
	# Compilando e gerando o executavel
	gcc main.c disco.o -o main
	
	# Executando
	./main

clean:
	rm *.o
	rm main
